//GET Auctioneers List
export const GET_BIDDER_REQUESTED = "GET_BIDDER_REQUESTED";
export const GET_BIDDER_SUCCESS = "GET_BIDDER_SUCCESS";
export const GET_BIDDER_FAIL = "GET_BIDDER_FAIL";

//GET Auctioneer object
export const GET_BIDDER_DETAILS_REQUESTED = "GET_BIDDER_DETAILS_REQUESTED";
export const GET_BIDDER_DETAILS_SUCCESS = "GET_BIDDER_DETAILS_SUCCESS";
export const GET_BIDDER_DETAILS_FAIL = "GET_BIDDER_DETAILS_FAIL";

// Add Auctioneer
export const ADD_BIDDER_REQUESTED = "ADD_BIDDER_REQUESTED";
export const ADD_BIDDER_SUCCESS = "ADD_BIDDER_SUCCESS";
export const ADD_BIDDER_FAIL = "ADD_BIDDER_FAIL";

// update Auctioneer
export const UPDATE_BIDDER_REQUESTED = "UPDATE_BIDDER_REQUESTED";
export const UPDATE_BIDDER_SUCCESS = "UPDATE_BIDDER_SUCCESS";
export const UPDATE_BIDDER_FAIL = "UPDATE_BIDDER_FAIL";

// delete Auctioneer
export const DELETE_BIDDER_REQUESTED = "DELETE_BIDDER_REQUESTED";
export const DELETE_BIDDER_SUCCESS = "DELETE_BIDDER_SUCCESS";
export const DELETE_BIDDER_FAIL = "DELETE_BIDDER_FAIL";

//search auctioneer

export const SEARCH_BIDDER_REQUESTED = "SEARCH_BIDDER_REQUESTED";
export const SEARCH_BIDDER_SUCCESS = "SEARCH_BIDDER_SUCCESS";
export const SEARCH_BIDDER_FAIL = "SEARCH_BIDDER_FAIL";