//GET Auctioneers List
export const GET_AUCTIONHOUSE_REQUESTED = "GET_AUCTIONHOUSE_REQUESTED";
export const GET_AUCTIONHOUSE_SUCCESS = "GET_AUCTIONHOUSE_SUCCESS";
export const GET_AUCTIONHOUSE_FAIL = "GET_AUCTIONHOUSE_FAIL";
