//GET Auctionhouse List
export const GET_AUCTIONHOUSE_REQUESTED = "GET_AUCTIONHOUSE_REQUESTED";
export const GET_AUCTIONHOUSE_SUCCESS = "GET_AUCTIONHOUSE_SUCCESS";
export const GET_AUCTIONHOUSE_FAIL = "GET_AUCTIONHOUSE_FAIL";

//Get Auction House Details
export const GET_AUCTIONHOUSEDETAILS_REQUESTED = "GET_AUCTIONHOUSEDETAILS_REQUESTED";
export const GET_AUCTIONHOUSEDETAILS_SUCCESS = "GET_AUCTIONHOUSEDETAILS_SUCCESS";
export const GET_AUCTIONHOUSEDETAILS_FAIL = "GET_AUCTIONHOUSEDETAILS_FAIL";
