//GET Auctioneers List
export const GET_AUCTIONEERS_REQUESTED = "GET_AUCTIONEERS_REQUESTED";
export const GET_AUCTIONEERS_SUCCESS = "GET_AUCTIONEERS_SUCCESS";
export const GET_AUCTIONEERS_FAIL = "GET_AUCTIONEERS_FAIL";

//GET Auctioneer object
export const GET_AUCTIONEER_DETAILS_REQUESTED = "GET_AUCTIONEER_DETAILS_REQUESTED";
export const GET_AUCTIONEER_DETAILS_SUCCESS = "GET_AUCTIONEER_DETAILS_SUCCESS";
export const GET_AUCTIONEER_DETAILS_FAIL = "GET_AUCTIONEER_DETAILS_FAIL";

// Add Auctioneer
export const ADD_AUCTIONEER_REQUESTED = "ADD_AUCTIONEER_REQUESTED";
export const ADD_AUCTIONEER_SUCCESS = "ADD_AUCTIONEER_SUCCESS";
export const ADD_AUCTIONEER_FAIL = "ADD_AUCTIONEER_FAIL";

// update Auctioneer
export const UPDATE_AUCTIONEER_REQUESTED = "UPDATE_AUCTIONEER_REQUESTED";
export const UPDATE_AUCTIONEER_SUCCESS = "UPDATE_AUCTIONEER_SUCCESS";
export const UPDATE_AUCTIONEER_FAIL = "UPDATE_AUCTIONEER_FAIL";

// delete Auctioneer
export const DELETE_AUCTIONEER_REQUESTED = "DELETE_AUCTIONEER_REQUESTED";
export const DELETE_AUCTIONEER_SUCCESS = "DELETE_AUCTIONEER_SUCCESS";
export const DELETE_AUCTIONEER_FAIL = "DELETE_AUCTIONEER_FAIL";